project:
  type: website
  output-dir: docs

website:
  title: "Open Payments"
  sidebar:
    contents:
      - href: index.qmd
        text: Home

format:
  html:
    theme: [cosmo, styles.scss]
    mainfont: Archivo
    toc: true



